# Generated by Django 3.0.10 on 2021-02-21 10:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=False)),
                ('from_address', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=30, null=True)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['created_at', 'from_address'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TO', 'To'), ('CC', 'Cc'), ('BCC', 'Bcc')], default='TO', max_length=4)),
                ('address', models.EmailField(max_length=254)),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mails.Mail')),
            ],
            options={
                'ordering': ['type', 'address'],
                'unique_together': {('mail', 'type', 'address')},
            },
        ),
    ]
