# Generated by Django 3.0.10 on 2021-02-21 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0002_mail_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='body',
            new_name='body_html',
        ),
        migrations.AddField(
            model_name='mail',
            name='body_text',
            field=models.TextField(default='placeholder'),
            preserve_default=False,
        ),
    ]
