# Generated by Django 3.0.10 on 2021-02-21 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0004_auto_20210221_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Outbox',
        ),
    ]
