# Generated by Django 3.0.10 on 2021-02-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mails', '0005_auto_20210221_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='sent_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
